name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/726010183755/locations/global/workloadIdentityPools/rearc-quest-wif-pool/providers/github-provider"
          service_account: "rearc-deployer@rearc-quest-project.iam.gserviceaccount.com"
          audience: "https://github.com/sfestic89/rearc-quest"

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker europe-west3-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t europe-west3-docker.pkg.dev/rearc-quest-project/rearc-quest/rearc-app:latest .
          docker push europe-west3-docker.pkg.dev/rearc-quest-project/rearc-quest/rearc-app:latest