name: Terraform CI/CD

on:
  push:
    branches:
      # This branch will trigger the 'plan' job
      - rearch-quest-branch
      # This branch will trigger the 'apply' job
      - main
  # Allow manual triggering of the workflow from the GitHub UI
  workflow_dispatch:

jobs:
  # Job 1: Terraform Plan
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    
    # This job will run on pushes to 'rearch-quest-branch' or manual dispatch.
    if: github.ref == 'refs/heads/rearch-quest-branch' || github.event_name == 'workflow_dispatch'

    permissions:
      contents: read
      id-token: write # Required for Workload Identity Federation

    defaults:
      run:
        shell: bash
        working-directory: ./infrastructure

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Authenticate to GCP using Workload Identity Federation
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/726010183755/locations/global/workloadIdentityPools/cloud-infra-github-pool/providers/cloud-infra-github-pool"
          service_account: "ccoegithub-terraform@ccoe-seed-project.iam.gserviceaccount.com"


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan

  # Job 2: Terraform Apply
  terraform-apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    
    # This job will run on pushes to 'main'
    if: github.ref == 'refs/heads/main'

    permissions:
      contents: read
      id-token: write

    defaults:
      run:
        shell: bash
        working-directory: ./infrastructure

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/726010183755/locations/global/workloadIdentityPools/cloud-infra-github-pool/providers/cloud-infra-github-pool"
          service_account: "ccoegithub-terraform@ccoe-seed-project.iam.gserviceaccount.com"

          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate
        
      - name: Terraform Apply
        run: terraform apply -auto-approve